root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o /financial-control-backend app/server.go
bin = "/"

full_bin = "/financial-control-backend"

log = "air_errors.log"

include_ext = ["go", "yaml"]

delay = 1000

[log]
time = true

[misc]
clean_on_exit = true
