version: "3.4"

services:
  api:
    container_name: financial-control-backend
    build:
      context: .
      target: dev
    ports:
      - "8001:8080"
      - "2345:2345"
    volumes:
      - .:/app:rw,delegated
    networks:
      - financial_control_network
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=:8080

  db:
      image: postgres:14.4-alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

networks:
  financial_control_network:
